name: Documentation

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
            activate-environment: my-env
            environment-file: deploy/conda/env.yml
            auto-activate-base: false

      - name: Install Tree
        run: sudo apt-get install tree -y

      - name: Display Tree Before Building
        run: tree

      - name: Build Package
        run: |
          pip install build
          python -m build

      - name: Build docs using sphinx
        run: |
            pip install -e .
            cd docs
            sphinx-apidoc -o ./source ../src/HousePricePrediction/
            make html
            cd ..

      - name: Display Tree After Building
        run: tree

      - name: Upload Build docs
        uses: actions/upload-artifact@v4
        with:
          name: html_arti
          path: docs/build/html

