name: unit-testing

on:
  pull_request:
    branches:
      - main

jobs:
    unitTest:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash -el {0}

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Miniconda
          uses: conda-incubator/setup-miniconda@v2
          with:
            activate-environment: my-env
            environment-file: deploy/conda/env.yml
            auto-activate-base: false

        - name: install tree cli tool
          run: |
            sudo apt-get install tree

        - name: Display the directory tree After building
          run: |
            tree .

        - name: install the package
          run: |
            pip install -e .
            pip install -U pytest

        - name: test using pytest
          run: |
            pytest