name: Build Package and Run Tests

on:
  pull_request:
    branches:
      - main
jobs:
  build_and_test:
    name: build and test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: my-env
          environment-file: deploy/conda/env.yml
          auto-activate-base: false

      - name: Install Tree
        run: |
          pip install setuptools
          pip install build
          sudo apt install tree

      - name: Display Tree After Building
        run: tree

      - name: Install Package in Dev Mode
        run: pip install -e

      - name: Installing Pytest
        run: pip install pytest

      - name: Run Tests
        run: pytest
        continue-on-error: true

      - name: Fail Workflow on Test Failures
        run: |
          if [ $? -eq 0 ]; then
            echo "All tests passed!"
            exit 0
          else
            echo "Some tests failed. Exiting with failure status."
            exit 1
          fi